package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"math"
	"os"
	"sort"
	"strings"
)

type columnSummaryConfig struct {
	ReportJSON string
	Out        string
}

func parseColumnSummaryFlags(args []string) (columnSummaryConfig, error) {
	cfg := columnSummaryConfig{
		ReportJSON: "results/report.json",
		Out:        "-",
	}
	fs := flag.NewFlagSet("column-summary", flag.ContinueOnError)
	flagUsage(fs, "Render the compact TreeDB column-store JSONBench summary table.")
	fs.StringVar(&cfg.ReportJSON, "report-json", cfg.ReportJSON, "Machine-readable report JSON generated by jsonbench_treedb report")
	fs.StringVar(&cfg.Out, "out", cfg.Out, "Markdown summary output path, or - for stdout")
	if err := fs.Parse(args); err != nil {
		return cfg, err
	}
	var err error
	cfg.ReportJSON, err = expandPath(cfg.ReportJSON)
	if err != nil {
		return cfg, err
	}
	if strings.TrimSpace(cfg.Out) != "" && cfg.Out != "-" {
		cfg.Out, err = expandPath(cfg.Out)
		if err != nil {
			return cfg, err
		}
	}
	return cfg, nil
}

func writeColumnSummary(cfg columnSummaryConfig) error {
	raw, err := os.ReadFile(cfg.ReportJSON)
	if err != nil {
		return err
	}
	var doc reportDocument
	if err := json.Unmarshal(raw, &doc); err != nil {
		return fmt.Errorf("parse %s: %w", cfg.ReportJSON, err)
	}
	md := renderColumnStoreCompactSummary(doc)
	if cfg.Out == "" || cfg.Out == "-" {
		_, err := os.Stdout.Write(md)
		return err
	}
	if err := os.MkdirAll(parentDir(cfg.Out), 0o755); err != nil {
		return err
	}
	return os.WriteFile(cfg.Out, md, 0o644)
}

func renderColumnStoreCompactSummary(doc reportDocument) []byte {
	rows := make([]reportRow, 0, len(doc.Rows))
	for _, row := range doc.Rows {
		if row.System != "TreeDB" {
			continue
		}
		switch row.StorageLayout {
		case storageLayoutColumnStore, storageLayoutColumnStorePrepared, storageLayoutColumnStorePreparedMetadata, storageLayoutColumnStoreFull, storageLayoutColumnStoreFullPrepared:
			rows = append(rows, row)
		}
	}
	sort.Slice(rows, func(i, j int) bool {
		a, b := rows[i], rows[j]
		if a.DatasetSize != b.DatasetSize {
			return a.DatasetSize < b.DatasetSize
		}
		if cmp := columnSummaryLayoutRank(a.StorageLayout) - columnSummaryLayoutRank(b.StorageLayout); cmp != 0 {
			return cmp < 0
		}
		if cmp := columnSummaryQueryRank(a.Query) - columnSummaryQueryRank(b.Query); cmp != 0 {
			return cmp < 0
		}
		if a.Projection != b.Projection {
			return a.Projection < b.Projection
		}
		return a.Query < b.Query
	})

	var buf bytes.Buffer
	if len(rows) == 0 {
		fmt.Fprintf(&buf, "No TreeDB column-store rows found.\n")
		return buf.Bytes()
	}
	fmt.Fprintf(&buf, "| layout | shape | mode | query | best | loaded rows/s | scanned rows | storage | load |\n")
	fmt.Fprintf(&buf, "|---|---|---|---:|---:|---:|---:|---:|---:|\n")
	for _, row := range rows {
		fmt.Fprintf(
			&buf,
			"| %s | %s | %s | %s | %s | %s | %s | %s | %s |\n",
			row.StorageLayout,
			columnSummaryDataShape(row),
			columnSummaryExecutionMode(row),
			row.Query,
			formatSeconds(row.BestSec),
			formatColumnSummaryRowsPerSecond(row),
			formatColumnSummaryCount(row.RowsScanned),
			formatBytes(row.StorageBytes),
			formatSeconds(row.LoadSec),
		)
	}
	fmt.Fprintf(&buf, "\nRows/sec is based on loaded logical rows. `full-retained-json` rows store enough JSON payload to reconstruct every loaded document; `query-shaped-projection` rows are smaller benchmark projections and are not full-storage baselines. `prepared metadata top-k` applies only to q4/q5 and answers from aggregate metadata with `scanned rows` = 0; `full-prepared bounded top-k` applies to full-retained q4/q5 and scans typed-column data with a bounded TopK request.\n")
	return buf.Bytes()
}

func columnSummaryLayoutRank(layout string) int {
	switch layout {
	case storageLayoutColumnStore:
		return 0
	case storageLayoutColumnStorePrepared:
		return 1
	case storageLayoutColumnStorePreparedMetadata:
		return 2
	case storageLayoutColumnStoreFull:
		return 3
	case storageLayoutColumnStoreFullPrepared:
		return 4
	default:
		return 100
	}
}

func columnSummaryExecutionMode(row reportRow) string {
	switch row.StorageLayout {
	case storageLayoutColumnStore:
		return "direct physical scan"
	case storageLayoutColumnStorePrepared:
		return "prepared physical scan"
	case storageLayoutColumnStorePreparedMetadata:
		if columnStoreUsesAggregateMetadata(row.StorageLayout, row.Query) {
			return "prepared metadata top-k"
		}
		return "prepared physical scan"
	case storageLayoutColumnStoreFull:
		return "direct physical scan"
	case storageLayoutColumnStoreFullPrepared:
		if columnStoreRequestsBoundedTopK(row.StorageLayout, row.Query) {
			return "full-prepared bounded top-k"
		}
		return "prepared physical scan"
	default:
		return ""
	}
}

func columnSummaryDataShape(row reportRow) string {
	if strings.TrimSpace(row.DataShape) != "" {
		return row.DataShape
	}
	if isFullDataColumnStoreLayout(row.StorageLayout) {
		return "full-retained-json"
	}
	return "query-shaped-projection"
}

func columnSummaryQueryRank(query string) int {
	switch query {
	case "q1":
		return 1
	case "q2":
		return 2
	case "q3":
		return 3
	case "q4":
		return 4
	case "q5":
		return 5
	default:
		return 100
	}
}

func formatColumnSummaryRowsPerSecond(row reportRow) string {
	if row.DatasetSize <= 0 || row.BestSec <= 0 || math.IsNaN(row.BestSec) || math.IsInf(row.BestSec, 0) {
		return ""
	}
	out := formatColumnSummaryFloat(float64(row.DatasetSize) / row.BestSec)
	if row.RowsScanned == 0 {
		out += " logical"
	}
	return out
}

func formatColumnSummaryCount(value int) string {
	if value == 0 {
		return "0"
	}
	return formatColumnSummaryFloat(float64(value))
}

func formatColumnSummaryFloat(value float64) string {
	abs := math.Abs(value)
	switch {
	case abs >= 1_000_000_000:
		return fmt.Sprintf("%.2fB", value/1_000_000_000)
	case abs >= 1_000_000:
		return fmt.Sprintf("%.1fM", value/1_000_000)
	case abs >= 1_000:
		return fmt.Sprintf("%.1fk", value/1_000)
	default:
		return fmt.Sprintf("%.0f", value)
	}
}
